package ua.syt0r.kanji.presentation.common.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFff5555)
val md_theme_light_onPrimary = Color(0xFFFCFCFC)
val md_theme_light_primaryContainer = Color(0xFFff5555)
val md_theme_light_onPrimaryContainer = Color(0xFFFCFCFC)
val md_theme_light_secondary = Color(0xFFff897c)
val md_theme_light_onSecondary = Color(0xFFFCFCFC)
val md_theme_light_secondaryContainer = Color(0xFFff5555)
val md_theme_light_onSecondaryContainer = Color(0xFFffffff)
val md_theme_light_tertiary = Color(0xFFff5555)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFFCFCFC)
val md_theme_light_onTertiaryContainer = Color(0xFF410004)
val md_theme_light_error = Color(0xFFff897c)
val md_theme_light_errorContainer = Color(0xFFFCFCFC)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFFCFCFC)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdbe4e6)
val md_theme_light_onSurfaceVariant = Color(0xFF3f484a)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeed)
val md_theme_light_inverseSurface = Color(0xFF362f2e)
val md_theme_light_inversePrimary = Color(0xFFFCFCFC)

val md_theme_dark_primary = Color(0xFFff5555)
val md_theme_dark_onPrimary = Color(0xFFffdad8)
val md_theme_dark_primaryContainer = Color(0xFFff5555)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdad7)
val md_theme_dark_secondary = Color(0xFFc00000)
val md_theme_dark_onSecondary = Color(0xFFffdad8)
val md_theme_dark_secondaryContainer = Color(0xFFff5555)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdad8)
val md_theme_dark_tertiary = Color(0xFFff5555)
val md_theme_dark_onTertiary = Color(0xFFffdad8)
val md_theme_dark_tertiaryContainer = Color(0xFF930012)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad8)
val md_theme_dark_error = Color(0xFFff5555)
val md_theme_dark_errorContainer = Color(0xFF201a1a)
val md_theme_dark_onError = Color(0xFFc00000)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a1a)
val md_theme_dark_onBackground = Color(0xFFecdfde)
val md_theme_dark_surface = Color(0xFF201a1a)
val md_theme_dark_onSurface = Color(0xFFecdfde)
val md_theme_dark_surfaceVariant = Color(0xFF534342)
val md_theme_dark_onSurfaceVariant = Color(0xFFd7c1c0)
val md_theme_dark_outline = Color(0xFFa08c8b)
val md_theme_dark_inverseOnSurface = Color(0xFF201a1a)
val md_theme_dark_inverseSurface = Color(0xFFecdfde)
val md_theme_dark_inversePrimary = Color(0xFFa33b3e)